### ISSUE TITLE
No document on how to build and run the source

### ISSUE THREAD

**Issue by ShanikaEdiriweera** [bregman-arie/reqwise#5]
When contributing to this project it is needed to modify the source code and rebuild and test the application. Therefore a proper document on how to build and run the source should be included in the repository.

**Comment by bregman-arie** [comment]
Hi Shanika,

First step is to install the project using 'pip install .' which already mentioned in the documentation.
Since this is a Python project, all you need to do is to modify the code and then run the program with 'reqwise'.

As for the tests - at the moment there is none. Any help with that would be appreciated.

Thank you,

Arie
